---

- git_config:
    name: user.email
    value: "{{var_git_email}}"

- git_config:
    name: user.name
    value: "{{var_git_name}}"

- name: Write global git ignore file
  copy:
    src: global-git-ignore
    dest: "/home/{{var_user}}/.global-git-ignore"
    owner: "{{var_user}}"
    group: "{{var_user}}"

- git_config:
    name: core.excludesfile
    value: "/home/{{var_user}}/.global-git-ignore"
