---

- name: Check if Golang already installed
  stat:
    path: /usr/local/go
  register: golang_cli

- name: Download Golang
  get_url:
    url: "https://dl.google.com/go/go{{var_go_version}}.{{var_kernel}}-{{var_arch}}.tar.gz"
    dest: "/tmp/golang.tar.gz"
    owner: "{{var_user}}"
    group: "{{var_user}}"
  when: not golang_cli.stat.exists

- name: Install Golang
  shell: tar -C /usr/local -xzf /tmp/golang.tar.gz
  when: not golang_cli.stat.exists

- name: Creating basic directories structure
  file:
    path: "/home/{{var_user}}/go"
    state: directory
    owner: "{{var_user}}"
    group: "{{var_user}}"
  when: not golang_cli.stat.exists
