---

- name: Check if JetBrains ToolBox already inst
  stat:
    path: /opt/jetbrains-toolbox/jetbrains-toolbox.sh
  register: jetbrains_toolbox

- name: Download JetBrains ToolBox
  get_url:
    url: "https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh"
    dest: "/tmp/jetbrains-toolbox.sh"
    mode: '0755'
  when: not jetbrains_toolbox.stat.exists

- name: Execute jetbrains-toolbox.sh
  shell: /tmp/jetbrains-toolbox.sh
  when: not jetbrains_toolbox.stat.exists

- name: Remove jetbrains-toolbox.sh
  file: path=/tmp/jetbrains-toolbox.sh state=absent
  when: not jetbrains_toolbox.stat.exists

- name: Install JetBrains ToolBox
  shell: /opt/jetbrains-toolbox/jetbrains-toolbox.sh
  become_user: "{{var_user}}"
  when: not jetbrains_toolbox.stat.exists
