---

- name: Check if Minikube is already installed
  stat:
    path: /tmp/minikube
    register: minikube

- name: Download Minikube
  get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
    dest: "/tmp/minikube"
    owner: "{{var_user}}"
    group: "{{var_user}}"
  when: not minikube.stat.exists

- name: Install Install
  shell: install /tmp/minikube /usr/local/bin/minikube
  when: not minikube.stat.exists
