---

- name: Check if oh my zsh is already instaled
  stat:
    path: "/home/{{var_user}}/.oh-my-zsh"
  register: oh_my_zsh_folder

- name: Cloning  oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "/home/{{var_user}}/.oh-my-zsh"
  become_user: "{{var_user}}"
  when: not oh_my_zsh_folder.stat.exists

- name: Check if zsh-autosuggestion already cloned
  stat:
    path: "/home/{{var_user}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  register: zsh_autosuggestions_folder

- name: Add zsh-autosuggestion plugin
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "/home/{{var_user}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become_user: "{{var_user}}"
  when: not zsh_autosuggestions_folder.stat.exists

- name: Build template of zshrc
  template:
    src: zshrc.j2
    dest: "/home/{{var_user}}/.zshrc"
    owner: "{{var_user}}"
    group: "{{var_user}}"
    backup: yes

- name: Set zsh as default
  shell: "sudo usermod -s $(which zsh) {{var_user}}"
