---

- name: Check if Rust already installed
  stat:
    path: "/home/{{var_user}}/.cargo/bin/cargo"
  register: rust_cli

- name: Download rust
  get_url:
    url: "https://sh.rustup.rs"
    dest: "/tmp/rust.sh"
    owner: "{{var_user}}"
    group: "{{var_user}}"
  when: not rust_cli.stat.exists

- name: Install rust
  shell: /tmp/rust.sh
  when: not rust_cli.stat.exists
