---

- name: Install Pip3
  dnf: name=python3-pip

- name: Install snapd
  dnf:
    name: snapd

- name: Create symbolic link for snapd home
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Start snapd server
  shell: "systemctl start snapd.service"

- name: Install basic repositories
  dnf:
    name: fedora-workstation-repositories

- name: Activate repository
  shell: "dnf config-manager --set-enabled google-chrome"

- name: Install Google Chrome
  dnf:
    name: google-chrome-stable

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Gnome teaks
  dnf:
    name: gnome-tweaks

- name: Install Vim
  dnf:
    name: vim

- name: Install ZSH
  dnf:
    name: zsh

- name: Install HTTPie
  dnf:
    name: httpie

- name: Install net-tools
  dnf:
    name: net-tools

- name: Install GCC
  dnf:
    name: gcc

- name: Install Spotify
  flatpak:
    name: com.spotify.Client

- name: Install Discord
  flatpak:
    name: com.discordapp.Discord
