---
- name: Add brave repository
  ansible.builtin.command: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/

- name: Import brave releases to RPM
  ansible.builtin.command: sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  
- name: Install Brave
  dnf:
    name: brave-browser

