---

- name: Install Pip3
  dnf: name=python3-pip

- name: Install basic repositories
  dnf:
    name: fedora-workstation-repositories

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Gnome teaks
  dnf:
    name: gnome-tweaks

- name: Install Vim Enhanced
  dnf:
    name: vim-enhanced
    
- name: Install Vim
  dnf:
    name: vim-X11

- name: Install ZSH
  dnf:
    name: zsh

- name: Install HTTPie
  dnf:
    name: httpie

- name: Install net-tools
  dnf:
    name: net-tools

- name: Install GCC
  dnf:
    name: gcc

- name: Install Spotify
  flatpak:
    name: com.spotify.Client

- name: Install Discord
  flatpak:
    name: com.discordapp.Discord

- name: Install DNF Plugins Core
  dnf:
    name: dnf-plugins-core

- name: Run brave playbook
  include_tasks: brave.yml
