---

- name: Install developer tools and configs
  debug:
    msg:
      - "User: {{var_user}}"
      - "Git name: {{var_git_name}}"
      - "Git email: {{var_git_email}}"
      - "Os Family {{ansible_facts['os_family']}}"

- name: Running ubuntu playbook
  include_tasks: ubuntu/main.yml
  when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"

- name: Running fedora playbook
  include_tasks: fedora/main.yml
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] == "Fedora"

- name: Running elementary playbook
  include_tasks: elementary/main.yml
  when: ansible_facts['os_family'] == "elementary OS"

- name: Running Pop!_OS playbook
  include_tasks: popos/main.yml
  when: ansible_facts['os_family'] == "Pop!_OS"
