---
- name: Work out the distribution
  command: lsb_release -sc
  register: distro_codename

- name : Install docker dependencies
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "gnupg-agent"
    state: present

- name: Add docker engine keys
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add repository docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{distro_codename}} stable"
    state: present

- name: Install docker engine
  apt:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
    update_cache: yes
    state: present
