---

- name: Install Snapd
  apt: name=snapd

- name: Install Pip3
  apt: name=python3-pip

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Gnome teaks
  apt:
    name: gnome-tweaks

- name: Install Vim
  apt:
    name: vim-gtk3

- name: Install XClip
  apt:
    name: xclip

- name: Install ZSH
  apt:
    name: zsh

- name: Install CURL
  apt:
    name: curl

- name: Install HTTPie
  apt:
    name: httpie

- name: Install net-tools
  apt:
    name: net-tools

- name: Install GCC
  apt:
    name: gcc

- name: Install Spotify
  flatpak:
    name: spotify

- name: Install Discord
  flatpak:
    name: discord

- name: Install Slack
  flatpak:
    name: com.slack.Slack

- name: Install API Transport HTTPS
  apt:
    name: apt-transport-https

- name: Run brave playbook
  include_tasks: brave.yml
