---

- name: Enable old CGroups
  shell: "grubby --update-kernel=ALL --args=\"systemd.unified_cgroup_hierarchy=0\""

- name: Whitelist docker in firewall for trusted zone
  firewalld:
    zone: trusted
    interface: docker0
    permanent: yes
    state: enabled

- name: Whitelist docker in firewall for fedora workstation zone
  firewalld:
    zone: FedoraWorkstation
    masquerade: yes
    permanent: yes
    state: enabled

- name: Install Docker Moby
  dnf:
    name: moby-engine

- name: Install Docker compose
  dnf:
    name: docker-compose
