---

- name: Enable old CGroups
  shell: "grubby --update-kernel=ALL --args=\"systemd.unified_cgroup_hierarchy=0\""

- name: Whitelist docker in firewall for trusted zone
  firewalld:
    zone: trusted
    interface: docker0
    permanent: yes
    state: enabled

- name: Whitelist docker in firewall for fedora workstation zone
  firewalld:
    zone: FedoraWorkstation
    masquerade: yes
    permanent: yes
    state: enabled

- name: Install Docker Moby
  dnf:
    name: moby-engine

- name: Install Docker compose
  dnf:
    name: docker-compose

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: "Set permissions for docker usage on user {{var_user}}"
  user:
    name: "{{var_user}}"
    groups: docker
    append: yes

- name: Check if CTOP is already installed
  stat:
    path: "/usr/local/bin/ctop"
  register: ctop

- name: Install CTOP
  get_url:
    url: 'https://github.com/bcicen/ctop/releases/download/v0.7.3/ctop-0.7.3-linux-amd64'
    dest: /usr/local/bin/ctop
    mode: '0755'
    owner: "{{var_user}}"
    group: "{{var_user}}"
  when: not ctop.stat.exists
