---

- name: Install Terminator
  dnf:
    name: terminator

- name: Add Lazygit repository
  shell: dnf copr enable atim/lazygit -y

- name: Install Lazygit
  dnf:
    name: lazygit

- name: Install RipGrep
  dnf:
    name: ripgrep

    - name: Install Python Dev
  dnf:
    name: python3-devel

- name: Install Postman
  flatpak:
    name: postman

- name: Install GitKraken
  flatpak:
    name: com.axosoft.GitKraken

- name: Install VSCode
  flatpak:
    name: com.visualstudio.code

- name: Install NodeJS
  dnf:
    name: nodejs

- name: Install Yarn
  dnf:
    name: yarnpkg

- name: Creating npm global directory
  file:
    path: "/home/{{var_user}}/.npm-global"
    state: directory
    owner: "{{var_user}}"
    group: "{{var_user}}"

- name: Add Lazygit repository
  shell: npm config set prefix '~/.npm-global'
